DROP SEQUENCE MEMBERNOSEQ;
DROP TABLE MYMEMBER;

CREATE SEQUENCE MEMBERNOSEQ;

-- 회원가입을 해야 로그인이 될 수 있도록
-- MYNAME을 MYMEMBERNAME에 연결

CREATE TABLE MYMEMBER(
	MEMBERNO NUMBER PRIMARY KEY,
	MEMBERID VARCHAR2(500) NOT NULL,
	MEMBERPW VARCHAR2(500) NOT NULL,
	MEMBERNAME VARCHAR2(500) NOT NULL
);

INSERT INTO MYMEMBER
VALUES(MEMBERNOSEQ.NEXTVAL, 'admin', 'admin1234', '관지라');

SELECT MEMBERNO, MEMBERID, MEMBERPW, MEMBERNAME
FROM MYMEMBER
ORDER BY MEMBERNO DESC;